replicaCount: 1

image:
  repository: ghcr.io/lavlabinfrastructure/eaglescope
  pullPolicy: IfNotPresent
  tag: "1.0.0"

service:
  type: ClusterIP
  port: 80

env: []

nameOverride: ""
fullnameOverride: ""

config:
  name: ""
  files: {}

landingPage:
  enabled: true
  customHtml: ""

ingress:
  enabled: true
  annotations: {}
  hosts: []
  tls: []

resources: {}
nodeSelector: {}
tolerations: []
affinity: []
