{{- if .Values.config.files }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eaglescope.configMapName" . }}
  labels:
    {{- include "eaglescope.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config.files }}
  {{ $key }}: |
{{ $value | nindent 8 }}
  {{- end }}
---
{{- end }}

{{- if .Values.landingPage.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eaglescope.fullname" . }}-landingpage
  labels:
    {{- include "eaglescope.labels" . | nindent 4 }}
data:
  index.html: |
    {{- if .Values.landingPage.customHtml }}
{{ .Values.landingPage.customHtml | indent 4 }}
    {{- else }}
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Eaglescope Landing Page</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <style>
            body {
                background-color: #f8f9fa;
            }
            .container {
                margin-top: 50px;
            }
            .card {
                border: none;
                border-radius: 0.75rem;
                box-shadow: 0 0.125rem 0.25rem rgba(0, 0, 0, 0.075);
            }
            .card-title {
                margin-bottom: 1.5rem;
            }
            .list-group-item {
                border: none;
            }
            .list-group-item a {
                color: #007bff;
                text-decoration: none;
            }
            .list-group-item a:hover {
                text-decoration: underline;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="card">
                <div class="card-body text-center">
                    <h1 class="card-title">Eaglescope Landing Page</h1>
                    <ul class="list-group list-group-flush">
                    {{- range $key, $value := .Values.config.files }}
                        <li class="list-group-item"><a href="/eaglescope/?configurl=config/{{ $key }}">{{ (regexReplaceAll "\\.[^.]+$" $key "") }}</a></li>
                    {{- end }}
                    </ul>
                </div>
            </div>
        </div>
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    </body>
    </html>
    {{- end }}
  nginx.conf: |
    map $http_x_forwarded_proto $real_scheme {
        default $http_x_forwarded_proto;
        ''      $scheme;
    }
    server {
      listen 80;
      absolute_redirect off;
      port_in_redirect off;
      location / {
        root /usr/share/nginx/html;
        index index.html;
      }
      location /eaglescope/ {
        rewrite ^/eaglescope(/.*)$ $1 break;
        proxy_pass http://localhost:1180;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $real_scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;

        proxy_redirect http:// $real_scheme://;
      }
      {{- range .Values.extraContainers }}
      location /{{ .name }}/ {
        rewrite ^/{{ .name }}(/.*)$ $1 break;
        {{- with (first .ports) }}
        proxy_pass http://localhost:{{ .containerPort }};
        {{ end }}

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $real_scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
        
        proxy_redirect http:// $real_scheme://;
      }
      {{- end }}
    }
{{- end }}
